### ISSUE TITLE
[Feature]: Expand test coverage for AsyncBoundary

### ISSUE THREAD

**Issue by tooooo1** [suspensive/react#103]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name: `suspensive/react`

### **Overview**

The test coverage for the `AsyncBoundary` component is currently insufficient. The given test case performs a simple rendering test, but there are no tests that verify whether the key features of `AsyncBoundary` work properly. Given that `AsyncBoundary` is a critical component that manages async loading states and error handling, it's essential that comprehensive tests are in place.

### **Describe the solution you'd like**

I propose adding tests for the async loading and error handling aspects of the `AsyncBoundary` component.

### **Additional context**

[AsyncBoundary test code](https://github.com/suspensive/react/blob/main/packages/react/src/AsyncBoundary.spec.tsx)

```tsx
// suspensive test code
import { render } from '@testing-library/react'

describe('test', () => {
  it('should test', () => {
    const TEST_TEXT = 'suspensive'
    const fixture = render(<div>{TEST_TEXT}</div>)

    expect(fixture.getByText(TEST_TEXT)).toBeInTheDocument()
  })
})
```

At present, our test code seems to exist only to fulfill the requirement of having test code. What we need is true testing that effectively validates our application's behavior. This will be instrumental in facilitating the next leap forward for our **Suspensive** service...

**Comment by manudeli** [comment]
@tooooo1 
Could you help us by adding test code for AsyncBoundary or any other apis?
