### ISSUE TITLE
[Feature]: Support @suspensive/swr

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#11]
### **Package Scope**
@suspensive/swr

- [ ] Add to an existing package
- [x] New package

Package name: swr

**Comment by manudeli** [comment]
@ChanhyukPark-Tech I think we should concentrate on suspenseCache of @suspensive/react. So Could I close this issue?

**Comment by manudeli** [comment]
No plan

**Comment by anaclumos** [comment]
Are there any updates to this decision?

**Comment by manudeli** [comment]
> Are there any updates to this decision?

Still I have no plan to support SWR. But do you have good idea or want to contribute about it?
