### ISSUE TITLE
[Feature]: I want something like CHANGELOG.md 

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [suspensive/react#16]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name:

### **Overview**

I'm actually using suspensive well because you provided me a good library. I'm looking forward to it more and more because you're continuing to update new features.
As a library user, I wonder what features have been added depending on the version. It would be nice if we could check the update log and so on somewhere other than PR or commit!

### **Describe the solution you'd like**

- github release ?

**Comment by manudeli** [comment]
@ChanhyukPark-Tech

I made monorepo in my personal GitHub to test below things
1. Using changeset cli
2. Using changeset bot in Pull Request
3. Auto generating CHANGELOG.md with changeset and GitHub Actions
4. Auto publishing monorepo libraries on npm with GitHub Actions

You motivated me to do exactly this. I want to find out the exact method within this weekend.

https://github.com/manudeli/monorepo-libraries-changeset-test
You can follow the tests I'm doing at this link. If you're interested, can help, or have any advice, I'd really appreciate it.
