### ISSUE TITLE
[Feature]: How about to use volta?

### ISSUE THREAD

**Issue by sungh0lim** [suspensive/react#171]
### **Package Scope**

- [x] Add to an existing package
- [ ] New package

Package name:

### **Overview**

- How about using volta instead of nvm?

**Comment by manudeli** [comment]
> How about using volta instead of nvm?

This is why I use [nvm](https://github.com/nvm-sh/nvm)
1. Popularity: Open source need to be contributed by everyone, so I thought familiar tool is better if comparing tool have same features
2. Deeper shell integration: automatic version selection (I don't know other tools offer this feature)
3. GitHub Actions support automatic node version selection by .nvmrc (not only nvm but I selected it because of popularity of it)

Actually I have no experience using volta. I'm curious why you recommend volta instead of nvm. explain why you?

**Comment by sungh0lim** [comment]
I think there was a misunderstanding due to my lack of explanation about volta.

- [Volta](https://github.com/volta-cli/volta) has 8.7k stars.
- If you write contributing.md and guide the installation of volta, you can reduce the hassle of using nvm every time. 
- It supoorts [action](https://github.com/volta-cli/action).

It would be better to understand if you look at the README.md on volta github.

**Comment by manudeli** [comment]
> If you write contributing.md and guide the installation of volta, you can reduce the hassle of using nvm every time.

NVM have same feature aka. [Deeper Shell Integration](https://github.com/nvm-sh/nvm#deeper-shell-integration). I setup and use it everyday in my local machine.

> It supoorts [action](https://github.com/volta-cli/action).

It's cool but actions/setup-node support reading node version from `.nvmrc`

> [Volta](https://github.com/volta-cli/volta) has 8.7k stars.

nvm have 70.3k stars too. and I guess every JavaScript developer have experience with nvm to use multiple node version. or may installed nvm too already. In other hand, regardless Volta got many stars but I think number of people have no experience with it is more than not.

So If Volta had super good features than nvm, I want to try it. but I couldn't find feature like it. If there is why using volta is better you think. Reopen and mention me with it please.

**Comment by sungh0lim** [comment]
Volta is made with rust so it is faster than nvm. Therefore, version switching for each project is fast. 
It also has the advantage of supporting various cross-platforms such as Windows and Unix shell. 
Change the things that need to be changed on your own without these things interfering with your workflow.

As mentioned above, nvm may be widely used, but it has some inconveniences like `load-nvmrc`. It's possible to use both at the same time, although testing will be needed. Thanks for the response and let me know if you think you need volta.

**Comment by manudeli** [comment]
then, Could you make Pull Request to add Volta in this repo? I want to be persuaded by code

**Comment by sungh0lim** [comment]
Sure, I will make PR and show you as much as I have time during the holidays.

**Comment by manudeli** [comment]
@sungh0lim I mentioned you to make you don't forget. resolve this issue when you have possible time please

**Comment by manudeli** [comment]
@sungh0lim I close this issue first, reopen please freely if need.
