### ISSUE TITLE
BaseErrorbounday fallback type is something wrong in @suspensive/react

### ISSUE THREAD

**Issue by jinn2u** [suspensive/react#2]
### Relevant code or config

```ts
fallback: ReactNode | ((props: { error: Error; reset: (...args: unknown[]) => void }) => ReactNode)
```
### Problem description:
fallback type has reset prop and it take arg as a factor. but It's not used anywhere

### Suggested solution: 
i think it works too
```ts
fallback: ReactNode | ((props: { error: Error; reset: () => void }) => ReactNode)
```

**Comment by manudeli** [comment]
@jinn2u, Great catch thanks.
Do you want to fix this type through Pull Request?

**Comment by manudeli** [comment]
@all-contributors please add @jinn2u for bug
