### ISSUE TITLE
[Feature]: Change issue template md to yml

### ISSUE THREAD

**Issue by minsoo-web** [suspensive/react#222]
### **Package Scope**

- [ ] Add to an existing package
- [ ] New package
- [x] .github

### **Overview**

why don't you use issue template with yml ?
It is so cool for DX who made issue

### **Describe the solution you'd like**

I suggest using yml template in ISSUE_TEMPLATE

### **Additional context**

ref here
https://github.com/function-and-mountain/functional-coding-nutshell/issues/new/choose
[bug case](https://github.com/function-and-mountain/functional-coding-nutshell/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5B%F0%9F%90%9E%5D+%EB%B2%84%EA%B7%B8%EC%97%90+%EB%8C%80%ED%95%9C+%EA%B0%84%EB%9E%B5%ED%95%9C+%EC%A0%9C%EB%AA%A9%EC%9D%84+%EC%9E%91%EC%84%B1%ED%95%B4%EC%A3%BC%EC%84%B8%EC%9A%94)
[yml code](https://github.com/function-and-mountain/functional-coding-nutshell/blob/main/.github/ISSUE_TEMPLATE/bug.yml?plain=1)

**Comment by manudeli** [comment]
Cool👍 Could you make Pull Request too?

**Comment by minsoo-web** [comment]
> Cool👍 Could you make Pull Request too?

Of course, it is my pleasure
