### ISSUE TITLE
[Feature]: Add Discord

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#248]
### **Package Scope**

- [x] Add to an existing package

Package name: @suspensive/docs

**Comment by manudeli** [comment]
@minsoo-web Could you lead us this?

**Comment by minsoo-web** [comment]
Of course! It is my pleasure

**Comment by manudeli** [comment]
@minsoo-web Could you share your approximate end date?

**Comment by minsoo-web** [comment]
Sorry for late reply. I will do this at least tomorrow

**Comment by manudeli** [comment]
Our new Discord https://discord.gg/cmz6NfrNCM

**Comment by minsoo-web** [comment]
I'm going to configure the Discord server more and close this issue. (Add apps, add web hooks, etc.)

**Comment by minsoo-web** [comment]
> @minsoo-web I remind you softly

Thank you, it's a work I've forgotten. I'll give you a notification after I finish this work
