### ISSUE TITLE
[Bug]: "No QueryClient set, use QueryClientProvider to set one" after adding @suspensive/react-query

### ISSUE THREAD

**Issue by PetrovaDaria** [suspensive/react#252]
### Package Scope

@suspensive/react-query

### Bug description

We used `react-query` in our monorepository project but after adding new dep `@suspensive/react-query` we started to receive error "No QueryClient set, use QueryClientProvider to set one" and white screen during local development in apps. It is a floating error, sometimes it appears and sometimes is disappears. The full description of problem is given in the demo-repository https://github.com/PetrovaDaria/rq-monorepo-demo

### Expected behavior

`@suspensive/react-query` doesn't broke local development with error "No QueryClient set, use QueryClientProvider to set one"

### To Reproduce

I created demo repo with main settings as in my production project which has this problem. Go to "How to reporduce it" section to find details.

https://github.com/PetrovaDaria/rq-monorepo-demo

### etc.

Also created issue in `@tanstack/query` repo https://github.com/TanStack/query/issues/6225

**Comment by manudeli** [comment]
I saw Tkdodo's response in https://github.com/TanStack/query/issues/6225#issuecomment-1774674250 but I think his response is not you want. because you don't want to force all apps in monorepo have same @tanstack/react-query's version.

Do you use yarn version 1 or node version 16?
I think you can solve this issue by using yarn version 3 or node version 18? so I added this Pull Request(https://github.com/PetrovaDaria/rq-monorepo-demo/pull/1) to resolve your issue. Check this please.

**Comment by PetrovaDaria** [comment]
@manudeli thank you for a quick response, I'll check your solution. I forgot to add `.nvmrc`, we use node v16. What about yarn - we use v1 and I'm not sure if we can use v3. Some teammates tried to switch to v3 but they met a restriction in our organization's ui-kit package which didn't support yarn v3. But I need to clarify this moment. 

Also I didn't understand why node v18 and yarn v3 will help in this case.

**Comment by manudeli** [comment]
First of all, Test my solution(https://github.com/manudeli/rq-monorepo-demo) please. We should first check if this change completely solves your problem.

**Comment by manudeli** [comment]
@PetrovaDaria I close this issue. if need more conversation, reopen this issue again please
