### ISSUE TITLE
[BUG]: "Edit this page" link is wrong

### ISSUE THREAD

**Issue by ojj1123** [suspensive/react#26]
### **Package Scope**

Package name:

### **Describe the bug**

All the `Edit this page` links on every page of the official documentation are incorrect.
<img width="358" alt="스크린샷 2023-02-24 03 01 12" src="https://user-images.githubusercontent.com/33178048/220991377-2a55b052-b358-4402-9f85-b897ad3acaf6.png">

For example, the `Edit this page` link on [Motivation](https://docs.suspensive.org/docs/intro/motivation.i18n) page looks like this:
https://github.com/suspensive/react/docs/intro/motivation.i18n.md
<img width="692" alt="스크린샷 2023-02-24 02 57 12" src="https://user-images.githubusercontent.com/33178048/220990407-3391b503-79ce-4740-a64f-4ddda633c9c4.png">

The `Edit this page` links in the pages below all come out as 'Not Found'.
<img width="150" alt="스크린샷 2023-02-24 02 57 34" src="https://user-images.githubusercontent.com/33178048/220990509-80f100a1-4e23-4680-bf23-db0196919ab2.png">

Is document `i18n` still WIP?

**Comment by manudeli** [comment]
@ojj1123
I fixed this issue in https://github.com/suspensive/react/commit/a06f12d9f4cce3c87113e39947823f595cd20b2b
Thanks to you, I was able to find this bug and fix it. after fixing this bug, more people will be able to easily fix this official document.

Thanks! 👍
