### ISSUE TITLE
[Feature]: new public api documentation

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#30]
### **Package Scope**

- [x] Add to an existing package

Package name: @suspensive/react

### **Overview**

- [ ] Delay
- [ ] SuspensiveProvider, SuspensiveConfigs
- [ ] suspenseCache, useSuspenseCache

**Comment by manudeli** [comment]
> I'd like to know more about this problem!

I want to make documents about new features(Delay, SuspensiveProvider, suspenseCache, useSuspenseCache, etc.) of @suspensive/react

**Comment by ojj1123** [comment]
@manudeli 
Could you briefly explain what API suspenseCache is? Or could you leave some reference?
Just asking because I'm curious!

**Comment by manudeli** [comment]
> @manudeli Could you briefly explain what API suspenseCache is? Or could you leave some reference? Just asking because I'm curious!

@ojj1123 
Could you send me email? I want to meet you to explain suspenseCache plan in Discord
manudeli.ko@gmail.com
