### ISSUE TITLE
[Test]: useIsomorphicLayoutEffect Test Code

### ISSUE THREAD

**Issue by ssi02014** [suspensive/react#302]
### Package Scope

@suspensive/react

### Description
@manudeli @minsoo-web @okinawaa 👋
I was thinking about how I could test `useIsomorphicLayoutEffect`.

I eventually found a way to test it, but it required `two test files`.
If I wrote to the same file, the test kept failing, which was very stressful for me..... 🫠🫠🫠🫠

What do you think of this approach? Would it be worth adding as test code? 🤔

Or is there a better way to do it? I tried several methods, but this was the best I could come up with. 😭

## 1. useIsomorphicLayoutEffect.client.spec
```ts
import { useLayoutEffect } from 'react'

describe('useIsomorphicLayoutEffect', () => {
  it('should return useLayoutEffect in client environment', async () => {
    const { useIsomorphicLayoutEffect } = await import('./useIsomorphicLayoutEffect')
    expect(useIsomorphicLayoutEffect).toEqual(useLayoutEffect)
  })
})
```

## 2. useIsomorphicLayoutEffect.server.spec
```ts
import { useEffect } from 'react'

describe('useIsomorphicLayoutEffect', () => {
  it('should return useEffect in server environment', async () => {
    Object.defineProperty(global, 'window', {
      value: undefined,
    })

    const { useIsomorphicLayoutEffect } = await import('./useIsomorphicLayoutEffect')
    expect(useIsomorphicLayoutEffect).toEqual(useEffect)
  })
})
```

**Comment by ssi02014** [comment]
@manudeli 
Sadly, writing to the same file kept failing the test.... This was too much stress for me. 🫠🫠🫠🫠

**Comment by manudeli** [comment]
Ahha... could you make it as draft Pull Request? whether one files or two files is okay for me just make me easily check it as code.

**Comment by ssi02014** [comment]
@manudeli I found a way to test with one file!
