### ISSUE TITLE
[Feature] Create a page that summarizes the changes that will be deleted and will be added in v2

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#400]
> Oh, I got it. I didn't see [this change](https://github.com/suspensive/react/pull/346/files#diff-1cee8646d2cfba37d6ce6a6e9a8d16f8caba0b99fc3a1ad0cb997ed8c7384d2e) in detail and misunderstood it. 
> 
> However, why don't you state that the opinion you want to add is that it is going to be depreciated rather than deleted from the official document? I think it's okay to delete the export syntax together.
> 
> Alternatively, you can create a page that summarizes the changes that will be deleted and will be added!  
> 
> ref: https://chakra-ui.com/getting-started/migration#5-deprecated-features. 
https://nextjs.org/docs/app/api-reference/next-config-js/exportPathMap. 
https://react.dev/reference/react/legacy
https://mui.com/material-ui/migration/migration-v3/#button.

_Originally posted by @minsoo-web in https://github.com/suspensive/react/pull/346#discussion_r1402893357_

**Comment by manudeli** [comment]
@minsoo-web could I know plan for this?

**Comment by minsoo-web** [comment]
> @minsoo-web could I know plan for this?

I forgot. I'll finish the work by today
