### ISSUE TITLE
[Feature]: test all correctly with coverage

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#62]
### **Package Scope**

- [x] Add to an existing package

Package name:

**Comment by ChanhyukPark-Tech** [comment]
I will make test code for [Delay](https://github.com/suspensive/react/blob/main/packages/react/src/Delay.tsx) Component

**Comment by manudeli** [comment]
I'll close this issue because we achieved 100% test coverage🎉
Thanks to you guys @okinawaa @tooooo1
