### ISSUE TITLE
[Bug]: Including an object of type UseQueryOptions with select in the queries of useSuspenseQueries results in a type error.

### ISSUE THREAD

**Issue by wes5510** [suspensive/react#767]
### Package Scope

@suspensive/react-query

### Bug description

Including an object of type UseQueryOptions with select in the queries of useSuspenseQueries results in a type error.
<img width="1236" alt="image" src="https://github.com/suspensive/react/assets/7649777/b8d955e0-c8fa-4355-bffc-b5936cdd2522">

For your reference, the type of useGetStringQueryObject is as follows in the picture below.
<img width="569" alt="image" src="https://github.com/suspensive/react/assets/7649777/eaf2a1b2-dcef-4d7a-b673-4414a42e0b90">

### Expected behavior

There should not be a type error, and the data should be of type string.

### To Reproduce
**tsc --v: Version 4.9.5**

Please refer to the code below :)
```ts
type QueryOptions<T> = UseQueryOptions<Some, unknown, T>;

type Some = {
  id: string;
  createdAt: Date;
};

function useGetSomeQueryObject<T = Some>(
  options?: QueryOptions<T>
): Omit<QueryOptions<T>, "enabled"> {
  return {
    staleTime: Infinity,
    ...options,
    queryKey: ["a", "b"],
    queryFn: () =>
      Promise.resolve({
        id: `${new Date().valueOf()}`,
        createdAt: new Date(),
      }),
  };
}

function useGetStringQueryObject() {
  return useGetSomeQueryObject({
    select: (data) => data.id,
  });
}

const [{ data: string1 }] = useSuspenseQueries({
  queries: [useGetStringQueryObject()], // Type error occurred!
});
```

### Possible Solution

Modifying `select: (data....` to `select?: (data...` in the code below seems to solve the issue.
https://github.com/suspensive/react/blob/08bb5f25f8cf17e61f94d492b505b11d38fe7db0/packages/react-query/src/useSuspenseQueries.ts#L32-L39
It appears that TanStack's React Query has made a similar adjustment. [Link](https://github.com/TanStack/query/pull/6454)

**Comment by manudeli** [comment]
@wes5510 Could you share plan to fix this issue? I want to know your any opinion

**Comment by wes5510** [comment]
@manudeli 
Apologies for the delayed response.
This error is caused by a conflict between the QueryOptions type (select?: ...) and the useSuspenseQueries function's type (select: ...) inference. I started to modify to fix this, but stopped because I think it's better to let the useSuspenseQueries function be responsible for type inference. In other words, I think it's better to use plain objects as arguments to the useSuspenseQueries function, which means that in the example above, i'm using a plain object rather than a QueryOptions type.

However, our team has noticed that VS Code does not autocomplete when using plain objects as arguments to the useSuspenseQuery function. To compensate for this, we plan to create a queryOptions function that does type inference entirely.

**Comment by manudeli** [comment]
> I think it's better to use plain objects as arguments to the useSuspenseQueries function, which means that in the example above, i'm using a plain object rather than a QueryOptions type.
>
> However, our team has noticed that VS Code does not autocomplete when using plain objects as arguments to the useSuspenseQuery function. To compensate for this, we plan to create a queryOptions function that does type inference entirely.

@wes5510 

We are preparing [beta version of @suspensive/react-query](https://beta.suspensive.org/docs/react-query/migrate-to-v2), ([korean](https://beta.suspensive.org/ko/docs/react-query/migrate-to-v2)), I think we should add queryOptions function in @suspensive/react-query v2 for DX of people using @tanstack/react-query v4

I want to make you co-author for these work When I make Pull Request for it! If you okay, I want to get your review for this PR. Let's improve all of these issue in Suspensive v2. So much thanks to you report this issue.

**Comment by wes5510** [comment]
Sure, I'd be happy to help with PR reviews whenever you need them. Thank you. 👍 
@manudeli
