### ISSUE TITLE
[BUG]: fix useSuspenseCache tearing with startTransition, adopt useSyncExternalStore

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#80]
### **Package Scope**

- [x] Add to an existing package

Package name: @suspensive/react

### **Overview**

https://github.com/reactwg/react-18/discussions/86

Implement fixing with compatiable react 17 or under with this library
https://www.npmjs.com/package/use-sync-external-store

#### Reference
react-redux's solution https://github.com/reduxjs/react-redux/blob/master/package.json#L77

**Comment by okinawaa** [comment]
@manudeli 

If We don't solve this, do We have a lot of problems using `useSuspenseCache`?

Could you explain more specifically about the tearing issue I realized what kind of issue it is, but I haven't experienced the UI being twisted in real life. 

I was wondering if there were any really frequent tearing issues! in real application 😄

Thank you for discovering such a good problem and trying to solve it!

**Comment by manudeli** [comment]
Some people may think that the tearing issue is not a big problem. However, in applications where data accuracy is important, like bank application etc., the tearing issue causes the problem of not accurately synchronizing the current external store state, and I think this can be treated as a big problem. We are in a position to manage library that use external store such as Await. If there is a way to solve it, I think solving this problem is the right direction.

We can check [this video](https://youtu.be/oPfSC5bQPR8?feature=shared&t=559) to understand what is tearing issue of concurrent feature in React

We can check in [this discussion](https://github.com/reactwg/react-18/discussions/113) other libraries following this useSyncExternalStore

By the way, I tried to reproduce the tearing problem in our suspensive for even 3 hours, but I could not🥲. If I can reproduce it in the future, I would like to do it.
