### ISSUE TITLE
[Feature]: Docs with search by algolia's DocSearch

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#87]
### **Package Scope**

- [x] Add to an existing package

Package name: docs

**Comment by manudeli** [comment]
@ChanhyukPark-Tech, I am adding this feature in suspensive.org. I will add your email in algoria team member. check email if there is email from [algoria](https://www.algolia.com/)

**Comment by ChanhyukPark-Tech** [comment]
@manudeli thanks🥳
