### ISSUE TITLE
[Feature]: Storybook integration

### ISSUE THREAD

**Issue by manudeli** [suspensive/react#90]
### **Package Scope**

- [x] New package

Package name:

**Comment by ChanhyukPark-Tech** [comment]
Why do suspensive need a storybook? Aren't there not many situations where suspensive have to show the UI?

**Comment by manudeli** [comment]
> Why do suspensive need a storybook? Aren't there not many situations where suspensive have to show the UI?

I'm thinking of something similar to the issue below. We need to provide examples with user interaction, and I think storybooks are one of the good solutions, so I added this issue.

https://github.com/suspensive/react/issues/7
