### ISSUE TITLE
[BUG]: enabled prop doesn't change output data type

### ISSUE THREAD

**Issue by timsofteng** [suspensive/react#96]
### **Package Scope**
useSuspensiveQuery

Package name:
`@suspensive/react-query`

### **Describe the bug**
If `useSuspensiveQuery` has `enabled: boolean` param then it means `data` may be undefined (`DataType: TData | undefined`).
Howerver it is defined despite of `enabled` param. It may breaks component if user try to get some inner data like `data.someInnerKey`.
`Uncaught TypeError: Cannot read properties of undefined`

### **Expected behavior**
I guess the lib should mark data type as `TData | undefined` and status `"loading" | "success"` in case useSuspensiveQuery has `enabled` param.

**Comment by manudeli** [comment]
Could you reproduce it please as example code or any more comment?
I just want to clarify what you want to raise as issue.

You want to show me like below code?

```tsx
const boolean = Math.random() > 0.5

const query = useSuspenseQuery({
  queryKey: ['...'] as const,
  queryFn: () => { someInnerKey: 'someInnerKey' } as const,
  enabled: boolean,
})

query.data // TData | undefined, so you met "Uncaught TypeError: Cannot read properties of undefined" error?
```

query.data // TData | undefined, so You mean you met "Uncaught TypeError: Cannot read properties of undefined" error?
but, If the enabled option is boolean, Wouldn't it be right to come out as TData | undefined?

You can see how we test `return type of useSuspenseQuery` in [this file](https://github.com/suspensive/react/blob/main/packages/react-query/src/useSuspenseQuery.test-d.ts). check it out please. Could you clone this repository and show me what you expect to `return type of useSuspenseQuery`.

If you ok, Could you make Pull Request as what you expect please? I'd like to discuss this issue as exact code.

**Comment by manudeli** [comment]
I closed first. Reopen if you need please
